name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm install
      
      - name: Install client dependencies
        run: npm install --prefix client

      - name: Install server dependencies
        run: npm install --prefix server  
      
      - name: Build Client
        run: npm run build --prefix client
        
      - name: Build server
        run: npm run build --prefix server

      - name: Lint
        run: npx eslint "src/**/*.ts"